version: '3.8'
services:
  postgres:
    image: alexsuf/postgres
#    image: post
    container_name: postgres
    restart: always
    ports:
      - 1111:5432
      - 9100:9100
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
      TZ: Europe/Moscow
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./on_startup.sql:/docker-entrypoint-initdb.d/init.sql
      - ./files:/files
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
# ----------------------------------------------------------------
# Для запуска node exporter внутри контейнера, запустите команду:
#   docker exec -d postgres node_exporter
# ----------------------------------------------------------------

volumes:
  postgres_db:
    external: true